[project]
name = "definition-understanding"
version = "0.1.0"
description = "A project to evaluate how well LLMs understand word definitions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "nltk",
    "openai",
    "transformers",
    "torch",
    "jupyter",
    "pytest",
    "tqdm",
    "hf_transfer"
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "mypy",
    "flake8",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
